apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: traefik-cert-zhangyongqiao
spec:
  dnsNames:
    - api.zhangyongqiao.com
  secretName: auto-secret
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
    
